### ISSUE TITLE
No matching implementation for interface method "Compare(TObject;TObject):LongInt;" found

### ISSUE THREAD

**Issue by khismatullin** [lukaszcz/srcdoc#1]

**Comment by lukaszcz** [comment]
Thank you for reporting this. It seems something changed with the new releases of FPC or its stdlib, and this project no longer compiles. I'll try to fix it when I find some time.

**Comment by lukaszcz** [comment]
I think I fixed the issues now. You should first update PascalAdt to version 1.0.1, then compile srcdoc from the latest commit on master. It should work now. Let me know if it doesn't.
